---

## if mhn role was executed before, we want its handlers to be executed so service is ready to answer registration
- meta: flush_handlers

## some packages need multiverse like snmp-mibs-downloader
- name: Ubuntu | ensure multiverse repo are enabled
  apt_repository: repo="{{item}}"
  register: multiverse_installed
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu | update apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: multiverse_installed | changed

## check no issue but not idempotent...
#- command: 'dpkg --configure -a'

- name: Install MHN Client - amun
  include: deploy_amun.yml
  when: mhnclient_amun is defined and mhnclient_amun
  tags:
    - amun

## FIXME! centos7: 'DistributionNotFound: No distributions at all found for bacpypes (from conpot)'
- name: Install MHN Client - conpot
  include: deploy_conpot.yml
  when: mhnclient_conpot is defined and mhnclient_conpot and ansible_distribution == 'Ubuntu'
  tags:
    - conpot

- name: Install MHN Client - Dionaea
  include: deploy_dionaea.yml
  when: mhnclient_dionaea is defined and mhnclient_dionaea and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'precise')
  tags:
    - dionaea

#- debug: msg="Warning: Dionaea uses trusty only ppa and not compatible with others."
#  when: dionaea is defined and dionaea and ansible_distribution_release != 'trusty'

- name: Install MHN Client - elastichoney
  include: deploy_elastichoney.yml
  when: mhnclient_elastichoney is defined and mhnclient_elastichoney
  tags:
    - elastichoney

## FIXME! NOK centos7/php54, trusty/php55: https://github.com/mushorg/glastopf/issues/266
- name: Install MHN Client - glastopf
  include: deploy_glastopf.yml
  when: mhnclient_glastopf is defined and mhnclient_glastopf and ansible_distribution_release == 'xenial'
  tags:
    - glastopf

- fail: msg="FATAL! Can't set up kippo and cowrie on same box as using same network port (port {{ mhnclient_kippo_ssh_port }})."
  when: mhnclient_kippo is defined and mhnclient_kippo and mhnclient_cowrie is defined and mhnclient_cowrie and mhnclient_kippo_ssh_port == mhnclient_cowrie_ssh_port

- name: Install MHN Client - kippo
  include: deploy_kippo.yml
  when: mhnclient_kippo is defined and mhnclient_kippo
  tags:
    - kippo

- name: Install MHN Client - cowrie
  include: deploy_cowrie.yml
  when: mhnclient_cowrie is defined and mhnclient_cowrie
  tags:
    - cowrie

- name: Install MHN Client - p0f
  include: deploy_p0f.yml
  when: mhnclient_p0f is defined and mhnclient_p0f
  tags:
    - p0f

- name: Install MHN Client - shockpot
  include: deploy_shockpot.yml
  when: mhnclient_shockpot is defined and mhnclient_shockpot
  tags:
    - shockpot

- name: Install MHN Client - wordpot
  include: deploy_wordpot.yml
  when: mhnclient_wordpot is defined and mhnclient_wordpot
  tags:
    - wordpot

- name: Install MHN Client - snort
  include: deploy_snort.yml
  when: mhnclient_snort is defined and mhnclient_snort
  tags:
    - snort

