---

## if mhn role was executed before, we want its handlers to be executed so service is ready to answer registration
- meta: flush_handlers

## some packages need multiverse like snmp-mibs-downloader
- name: Ubuntu | ensure multiverse repo are enabled
  apt_repository: repo="{{ item }}"
  register: multiverse_installed
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates multiverse'
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu | update apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: multiverse_installed is changed

- name: add logrotate.d configuration
  copy:
    src: logrotate-mhnclient
    dest: /etc/logrotate.d/mhnclient
    mode: '0644'
    backup: yes

## check no issue but not idempotent...
#- command: 'dpkg --configure -a'

- name: Install MHN Client - amun
  include: deploy_amun.yml
  when: mhnclient_amun is defined and mhnclient_amun|bool
  tags:
    - amun

## FIXME! centos7: 'DistributionNotFound: No distributions at all found for bacpypes (from conpot)'
- name: Install MHN Client - conpot
  include: deploy_conpot.yml
  when: mhnclient_conpot is defined and mhnclient_conpot|bool and ansible_distribution == 'Ubuntu'
  tags:
    - conpot

- name: Install MHN Client - Dionaea
  include: deploy_dionaea.yml
  when: >
    mhnclient_dionaea is defined and mhnclient_dionaea|bool and
    (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'precise')
  tags:
    - dionaea

#- debug: msg="Warning: Dionaea uses trusty only ppa and not compatible with others."
#  when: dionaea is defined and dionaea and ansible_distribution_release != 'trusty'

- name: Install MHN Client - Raspberry Pi Dionaea
  include: deploy_raspberrypi.yml
  when: >
    mhnclient_raspberrypi is defined and mhnclient_raspberrypi|bool
    and ansible_architecture == "armv7l"

- name: Install MHN Client - elastichoney
  include: deploy_elastichoney.yml
  when: mhnclient_elastichoney is defined and mhnclient_elastichoney|bool
  tags:
    - elastichoney

## FIXME! NOK centos7/php54, trusty/php55: https://github.com/mushorg/glastopf/issues/266
- name: Install MHN Client - glastopf
  include: deploy_glastopf.yml
  when: >
    mhnclient_glastopf is defined and mhnclient_glastopf|bool and
    ansible_distribution_release == 'xenial'
  tags:
    - glastopf

- fail: msg="FATAL! Can't set up kippo and cowrie on same box as using same network port (port {{ mhnclient_kippo_ssh_port }})."
  when: >
    mhnclient_kippo is defined and mhnclient_kippo|bool and
    mhnclient_cowrie is defined and mhnclient_cowrie|bool and
    mhnclient_kippo_ssh_port == mhnclient_cowrie_ssh_port

- name: Install MHN Client - kippo
  include: deploy_kippo.yml
  when: mhnclient_kippo is defined and mhnclient_kippo|bool
  tags:
    - kippo

- name: Install MHN Client - cowrie
  include: deploy_cowrie.yml
  when: mhnclient_cowrie is defined and mhnclient_cowrie|bool
  tags:
    - cowrie

- name: Install MHN Client - p0f
  include: deploy_p0f.yml
  when: mhnclient_p0f is defined and mhnclient_p0f|bool
  tags:
    - p0f

- name: Install MHN Client - shockpot
  include: deploy_shockpot.yml
  when: mhnclient_shockpot is defined and mhnclient_shockpot|bool
  tags:
    - shockpot

- name: Install MHN Client - wordpot
  include: deploy_wordpot.yml
  when: mhnclient_wordpot is defined and mhnclient_wordpot|bool
  tags:
    - wordpot

- name: Install MHN Client - snort
  include: deploy_snort.yml
  when: mhnclient_snort is defined and mhnclient_snort|bool
  tags:
    - snort

- name: Install MHN Client - mtpot
  include: deploy_mtpot.yml
  when: mhnclient_mtpot is defined and mhnclient_mtpot|bool
  tags:
    - mtpot
