---

- name: MHN Client | registration
  include: registration.yml honeypot=p0f
- set_fact:
    deploy: /root/.registration_done-p0f

- name: Extract HPF_HOST from server_url
  shell: >
    set -o pipefail
    echo {{ server_url }} | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'
  args:
    executable: /bin/bash
  register: HPF_HOST
  changed_when: False
- name: Set fact HPF_PORT
  set_fact:
    HPF_PORT: 10000
- name: retrieve HPF_IDENT from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"identifier\"]'"
  register: HPF_IDENT
  changed_when: False
- name: retrieve HPF_SECRET from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"secret\"]'"
  register: HPF_SECRET
  changed_when: False
  no_log: true

- name: Ubuntu | Install p0f dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - supervisor
    - libpcap-dev
    - libjansson-dev
    - gcc
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Kali'

- name: yum | Install p0f dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - supervisor
    - supervisor
    - libpcap-devel
    - jansson-devel
    - "@Development tools"
  when: ansible_os_family == "RedHat"

- stat: path=/opt/p0f
  register: p0fdir
- name: git clone p0f
  git:
    repo=https://github.com/threatstream/p0f.git
    dest=/opt/p0f
    version=origin/hpfeeds
  when: not p0fdir.stat.exists
- stat: path=/opt/p0f/p0f
  register: p0finstall
- name: build p0f
  command: "{{ item }} chdir=/opt/p0f"
  with_items:
    - ./build.sh
  when: not p0finstall.stat.exists

- name: create p0f user
  user: name="p0f-user" home=/var/empty/p0f shell=/bin/nologin createhome=no system=yes

- name: check p0f directory permissions
  file: path=/var/empty/p0f state=directory mode=0755

- name: set p0f supervisor config
  template: "src=p0f.conf.j2 dest={{ supervisor_confdir }}/p0f.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update

## https://groups.google.com/forum/#!msg/modern-honey-network/vY0H7cj2vlE/uA0BlrpCBAAJ
- name: add extra filters to P0f
  replace: dest=/opt/p0f/p0f_wrapper.sh regexp='^FILTER="!(src host ${MY_ADDRESS})"' replace='FILTER="(not src host ${MY_ADDRESS}) and {{ mhnclient_p0f_filters }}"' backup=yes
  when: mhnclient_p0f_filters is defined and mhnclient_p0f_filters != ''
  notify:
    - supervisor update
