---

- name: MHN Client | registration
  include: registration.yml honeypot=elastichoney
- set_fact:
    deploy: /root/.registration_done-elastichoney

- name: Extract HPF_HOST from server_url
  shell: |
    set -o pipefail
    echo {{ server_url }} | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'
  args:
    executable: /bin/bash
  register: HPF_HOST
  changed_when: False
- name: Set fact HPF_PORT
  set_fact:
    HPF_PORT: 10000
- name: retrieve HPF_IDENT from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"identifier\"]'"
  register: HPF_IDENT
  changed_when: False
- name: retrieve HPF_SECRET from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"secret\"]'"
  register: HPF_SECRET
  changed_when: False
  no_log: true

- name: Ubuntu | Install elastichoney dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - supervisor
## use golang role
#    - golang
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Kali'

- name: yum | Install elastichoney dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - supervisor
## use golang role
#    - golang-bin
  when: ansible_os_family == "RedHat"

- stat: path=/opt/elastichoney
  register: elastichoneydir
- name: git clone elastichoney
  git:
    repo=https://github.com/threatstream/elastichoney.git
    dest=/opt/elastichoney
  when: not elastichoneydir.stat.exists

- stat: path=/opt/elastichoney/elastichoney
  register: stgo
- name: build elastichoney
  shell: "{{ item }} chdir=/opt/elastichoney"
  with_items:
    - 'go get || true'
    - 'go build'
  environment:
    GOPATH: /opt/elastichoney
    GOBIN: /usr/bin
  when: not stgo.stat.exists

- name: set up elastichoney json config
  template: src=elastichoney-config.json.j2 dest=/opt/elastichoney/config.json mode=0644 backup=yes
  notify:
    - supervisor update

- name: set elastichoney supervisor config
  copy: "src=elastichoney.conf dest={{ supervisor_confdir }}/elastichoney.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update

- name: ensure elastichoney log dir exists
  file: dest=/var/log/elastichoney state=directory mode=0755
