---

- name: MHN Client | registration
  include: registration.yml honeypot=conpot
- set_fact:
    deploy: /root/.registration_done-conpot

- name: Extract HPF_HOST from server_url
  shell: >
    set -o pipefail
    echo {{ server_url }} | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'
  args:
    executable: /bin/bash
  register: HPF_HOST
  changed_when: False
- name: Set fact HPF_PORT
  set_fact:
    HPF_PORT: 10000
- name: retrieve HPF_IDENT from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"identifier\"]'"
  register: HPF_IDENT
  changed_when: False
- name: retrieve HPF_SECRET from registration file
  shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"secret\"]'"
  register: HPF_SECRET
  changed_when: False
  no_log: true

- name: Ubuntu | Install conpot dependencies
  apt:
    name:
      - git
      - libsmi2ldbl
      - snmp-mibs-downloader
      - python-pip
      - python-dev
      - libxml2-dev
      - libxslt-dev
      - libmysqlclient-dev
      - zlib1g-dev
      - python-virtualenv
      - supervisor
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install conpot dependencies
  yum:
    name:
      - git
      - supervisor
      - python-pip
      - python-devel
      - python-virtualenv
      - libxml2-devel
      - libxslt-devel
      - mariadb-devel
      - zlib-devel
## FIXME! rpm not available
#      - libsmi2ldbl
#      - snmp-mibs-downloader
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

#- name: Ensure distribute is present
#  pip: name=distribute state=present

- name: Install conpot virtualenv - setuptools
  pip: name=setuptools
    virtualenv=/opt/conpot/env
    version=26.1.1

- name: Install conpot virtualenv - rpyc for scapy #622
  pip:
    name: rpyc
    virtualenv: /opt/conpot/env
    version: 3.4.4

- name: Install conpot virtualenv
  pip: name="{{ item }}"
    virtualenv=/opt/conpot/env
  with_items:
#    - setuptools
    - pycrypto
    - git+https://github.com/threatstream/hpfeeds.git#egg=hpfeeds-dev
    - git+https://github.com/glastopf/modbus-tk.git#egg=modbus-tk==0.4

- name: Install conpot virtualenv
  pip:
    name: conpot
    version: 0.5.2
    virtualenv: /opt/conpot/env

- name: set conpot config
  template: src=conpot.cfg.j2 dest=/opt/conpot/conpot.cfg mode=0644
  notify:
    - supervisor update

#- name: review http template xsd - xml validation
#  replace:
#    dest: "/opt/conpot/env/src/conpot/conpot/protocols/http/http.xsd"
#    regexp: ' type="xs:.*" name="port"'
#    replace: " type=\"xs:unsignedShort\" name=\"port\""
#    backup: yes

#- name: review http template
#  replace:
#    dest: "/opt/conpot/env/src/conpot/conpot/templates/{{ mhnclient_conpot_template }}/http/http.xml"
#    regexp: ' port=".*"'
#    replace: " port=\"{{ mhnclient_conpot_http_port }}\""
#    backup: yes
#    validate: "xmllint --schema /opt/conpot/env/src/conpot/conpot/protocols/http/http.xsd %s"
#  notify:
#    - supervisor update

- name: set conpot supervisor config
  template: "src=conpot.conf.j2 dest={{ supervisor_confdir }}/conpot.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update
