
- stat: path=/var/_mhn/mhn/server/config.py
  register: mhnkeyfile

- fail: msg="FATAL! missing mhnkeyfile /var/_mhn/mhn/server/config.py"
  when: not mhnkeyfile.stat.exists

- name: retrieve localhost deploy key
  command: sed -n "s/^DEPLOY_KEY = '\(.*\)'/\1/p" /var/_mhn/mhn/server/config.py
  register: deploykey
  changed_when: false
  args:
    warn: False

- set_fact:
    deploy_key: "{{ deploykey.stdout }}"

