---

- name: Install curl package for network registration
  package: name=curl state=present

## small hack to avoid registering multiple times
- stat: path="/root/.registration_done-{{ honeypot }}"
  register: done

## FIXME! if file contains '<title>502 Bad Gateway</title>', registration failed and should be attempt again
##	'raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded'
- name: register honeypot client on server
  shell: "curl {{ curl_arg }} -s -X POST -H \"Content-Type: application/json\" -d '{ \"name\": \"{{ ansible_hostname }}-{{ honeypot }}\", \"hostname\": \"{{ ansible_hostname }}\",  \"deploy_key\": \"{{ deploy_key }}\", \"honeypot\": \"{{ honeypot }}\" }' {{ server_url }}/api/sensor/ > /root/.registration_done-{{ honeypot }}"
  args:
    warn: False
  when: not done.stat.exists or done.stat.size == 0

- name: retrieve uuid from registration file
  command: "python -c 'import json;obj=json.load(file(\"/root/.registration_done-{{ honeypot }}\"));print obj[\"uuid\"]'"
  register: uuid
  failed_when: uuid.stdout == ''
  when: not done.stat.exists or done.stat.size == 0

- file: path="/root/.registration_done-{{ honeypot }}" state=touch
  when: not done.stat.exists or done.stat.size == 0

